{{- $s := .Release.Store }}
{{- $r := $s.registry }}

image:
  tag: 26.1.0-debian-12-r0
  tag: 26.0.8-debian-12-r1
  tag: {{ or $s.v "26.0.8" }}-{{ or $s.v_os "debian-12-r0" }} # https://hub.docker.com/r/bitnami/keycloak/tags
  {{- with $r.hostProxy }} 
  registry: {{ $r.hostProxy }}
  repository: {{ $r.proxy.docker }}/bitnami/keycloak
  {{- end }}

httpRelativePath: /auth/
ingress:
  enabled: true
  hostname: ""
  extraHosts:
    - name: ""
      path: /auth/

postgresql:
  enabled: false
externalDatabase:
  port: 5432
  database: keycloak
  user: postgres
  password: {{ $s.db.postgres }}
  host: {{ or $s.sql "sql1.db" }}

auth:
  adminPassword: {{ $s.oidc.password }}
  adminUser: admin

{{/* tls:
  enabled: true
  autoGenerated: true */}}
