{{- $s := .Release.Store }}
{{- $r := $s.registry }}

global:
  security:
    allowInsecureImages: true
    
image:
  tag: {{ or $s.v (index $s.ver (or $s.image .Release.Name)) }}
  {{- with $r.hostProxy }} 
  registry: {{ $r.hostProxy }}
  repository: {{ $r.proxy.docker }}/bitnami/keycloak
  {{- end }}

httpRelativePath: /auth/
ingress:
  enabled: true
  hostname: ""
  extraHosts:
    - name: ""
      path: /auth/

postgresql:
  enabled: false
externalDatabase:
  port: 5432
  database: keycloak
  user: postgres
  password: {{ $s.db.postgres }}
  host: {{ or $s.sql "sql1.db" }}

auth:
  adminPassword: {{ $s.oidc.password }}
  adminUser: admin

{{/* tls:
  enabled: true
  autoGenerated: true */}}
